"""
Runs a series of maintenance operations on the collection of entry files, updating the table of content files for
each category as well as creating a statistics file.

Counts the number of records each sub-folder and updates the overview.
Sorts the entries in the contents files of each sub folder alphabetically.
"""

# TODO add search which checks within an entry for similar dev names
# TODO add wikipedia (media search) for popular games at least
# TODO google search (for homepages or media entries) for popular games at least
# TODO search for xxx.sourceforge.net or io but not sourceforge.net/xxx in homepages as convenience
# TODO search for all with download or play field but without platform field
# TODO sort developers alphabetically in entry and remove duplicate developers
# TODO the output of the consistency check should go into a file
# TODO consistency check: report those with no popular first code repository service (popular=Github, Gitlab, Codeberg, gnomes, kde)
# TODO consistency check: report those with free assets license but not content open
# TODO consistency check: report those with content commercial as keyword but not commercial assets license
# TODO consistency check: report those with java as language but build system not gradle
# TODO consistency check: report those with c/c++ as language but build system not cmake
# TODO consistency check: report those with entry without screenshot (see entries/screenshot/readme.md)

import re
import datetime
import json
from utils import osg, osg_ui, osg_parse, utils, constants as c
import requests


def check_validity_backlog():
    """
    Check which links of the backlog are actually still valid anymore.
    Not used any more.
    """
    import requests

    # read backlog and split
    file = c.root_path / 'code' / 'backlog.txt'
    text = utils.read_text(file)
    urls = text.split('\n')
    urls = [x.split(' ')[0] for x in urls]

    headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64)'}
    for url in urls:
        try:
            r = requests.get(url, headers=headers, timeout=5)
        except Exception as e:
            print(f'{url} gave error: {e}')
        else:
            if r.status_code != requests.codes.ok:
                print(f'{url} returned status code: {r.status_code}')

            if r.is_redirect or r.history:
                print(f'{url} redirected to {r.url}, {r.history}')


def create_toc(title, file_name, entries):
    """
    Given a list of entries, a file name and a title, creates an markdown file with links to the entries.
    """
    # file path
    toc_file = c.tocs_path / file_name

    # header line
    text = f'[comment]: # (autogenerated content, do not edit)\n# {title}\n\n'

    # assemble rows
    rows = []
    for entry in entries:
        info = entry['Code language'] + entry['Code license'] + entry['State']
        rows.append(f"- **[{entry['Title']}]({'../' + entry['File'].name})** ({', '.join(info)})")

    # sort rows (by title)
    rows.sort(key=str.casefold)

    # add to text
    text += '\n'.join(rows)

    # write to toc file
    utils.write_text(toc_file, text)


def sort_text_file(file, name):
    """
    Reads a text file, splits in lines, removes duplicate lines, sorts them, writes back.
    """
    text = utils.read_text(file)
    text = text.split('\n')
    text = sorted(list(set(text)), key=str.casefold)
    print(f'{name} contains {len(text)} items')
    text = '\n'.join(text)
    utils.write_text(file, text)


class EntriesMaintainer:
    """
    Class for maintaining entries. Does have much internal state.
    """

    def __init__(self):
        """
        Initializes as without entries
        """
        self.entries = None

    def read_entries(self):
        """
        Simply read all the entries. Will raise an exception if some entries are malformed.
        """
        self.entries = osg.read_entries()
        print(f'{len(self.entries)} entries read')

    def write_entries(self):
        """
        Write all entries back.
        """
        if not self.entries:
            print('entries not yet loaded')
            return
        osg.write_entries(self.entries)
        print('entries written')

    def check_template_leftovers(self):
        """
        Very simple checks for template leftovers (that might result in false positives).
        Should be run only occasionally.
        """
        # load template and get all lines
        text = utils.read_text(c.root_path / 'template.md')
        text = text.split('\n')
        check_strings = [x for x in text if x and not x.startswith('##')]

        # iterate over all entries
        for _, entry_path, content in osg.entry_iterator():

            for check_string in check_strings:
                if content.find(check_string) >= 0:
                    print(f'{entry_path}: found {check_string}')
        print('checked for template leftovers')

    def _entry_label(self, entry):
        """
        Returns something meaningful to identify entries. Used in the inconsistency check.
        """
        if isinstance(entry, str):
            return entry
        return entry.get('Title', entry.get('File', ''))

    def _add_inconsistency_section(self, report_lines, title, entries):
        """
        Adds an inconsistency section for the inconsistency section.
        """
        labels = sorted(set(self._entry_label(entry) for entry in entries), key=str.casefold)
        report_lines.append(f'## {title}')
        report_lines.append(f'Count: {len(labels)}')
        if len(labels) > 0:
            report_lines.append(', '.join(labels))
        report_lines.append('')

    def _is_open_assets_license(self, license):
        """
        Definition of open (free to share, no price tag) assets license
        """
        if not isinstance(license, str):
            return False
        license = license.lower()  # normalize license
        if license in ('', '?', 'none', 'n/a'):
            return False
        if 'public domain' in license or 'cc0' in license:
            return True
        if 'proprietary' in license or 'custom' in license or 'commercial' in license:
            return False
        if 'creative commons' in license or license.startswith('cc') or license.startswith('cc-'):
            return 'nc' not in license and 'nd' not in license
        return True

    def _has_open_assets_license(self, entry):
        """
        Certain definition of open asset license.
        """
        licenses = entry.get('Assets license', [])
        if not licenses:
            return False
        return all(self._is_open_assets_license(license) for license in licenses)

    def _has_content_open_keyword(self, entry):
        """
        Is content open (might also be differently written)
        """
        return any('content open' in keyword.lower() for keyword in entry.get('Keyword', []))

    def _has_commercial_content_keyword(self, entry):
        """
        Is content commercial (might also be differently written)
        """
        return any('content commercial' in keyword.lower() for keyword in entry.get('Keyword', []))

    def _is_popular_code_repository(self, repo):
        """
        Popular code repository. Maybe move to constants.py
        """
        if not isinstance(repo, str):
            return False
        lowered = repo.lower()
        return any(host in lowered for host in ('bitbucket', 'codeberg', 'git.code.sf', 'gnu.org', 'nongnu.org', 'github', 'gitlab', 'gnome', 'kde'))

    def check_inconsistencies(self):
        """
        Some inconsistency checks.
        Writes a report to code/inconsistencies.txt.
        """
        if not self.entries:
            print('entries not yet loaded')
            return

        report_lines = []

        # Similar but unequal keywords
        keywords = []
        for entry in self.entries:
            keywords.extend(entry['Keyword'])

        keywords = [x if not x.startswith('multiplayer') else 'multiplayer' for x in keywords]
        keywords = [x if not x.startswith('content') else 'content' for x in keywords]

        unique_keywords = list(set(keywords))
        unique_keywords_counts = [keywords.count(l) for l in unique_keywords]
        similar_keyword_entries = []
        for index, name in enumerate(unique_keywords):
            for other_index in range(index + 1, len(unique_keywords)):
                other_name = unique_keywords[other_index]
                if osg.name_similarity(name, other_name) > 0.8:
                    similar_keyword_entries.append(f'{name} ({unique_keywords_counts[index]}) - {other_name} ({unique_keywords_counts[other_index]})')
        self._add_inconsistency_section(report_lines, 'Inconsistency: Similar but unequal keywords', similar_keyword_entries)

        # Code dependencies not included as entry
        valid_dependencies = list(c.general_code_dependencies_without_entry.keys())
        for entry in self.entries:
            if any((x in ('framework', 'library', 'game engine') for x in entry['Keyword'])):
                name = entry['Title']
                if name in c.code_dependencies_aliases:
                    valid_dependencies.extend(c.code_dependencies_aliases[name])
                else:
                    valid_dependencies.append(name)

        referenced_dependencies = {}
        for entry in self.entries:
            deps = entry.get('Code dependency', [])
            for dependency in deps:
                if dependency in referenced_dependencies:
                    referenced_dependencies[dependency] += 1
                else:
                    referenced_dependencies[dependency] = 1

        referenced_dependencies = [(k, v) for k, v in referenced_dependencies.items() if k not in valid_dependencies]
        referenced_dependencies.sort(key=lambda x: x[1], reverse=True)
        dependency_entries = [f'{dep} ({count})' for dep, count in referenced_dependencies]
        self._add_inconsistency_section(report_lines, 'Inconsistency: Code dependencies not included as entry', dependency_entries)

        # Has Play field but not Web as Platform
        play_platform_entries = []
        for entry in self.entries:
            if 'Play' in entry:
                if 'Platform' not in entry:
                    play_platform_entries.append(f'{entry["Title"]} (missing Platform)')
                elif 'Web' not in entry['Platform']:
                    play_platform_entries.append(f'{entry["Title"]} (missing Web platform)')
        self._add_inconsistency_section(report_lines, 'Inconsistency: Has Play field but not Web as Platform', play_platform_entries)

        # Java/Type/CoffeeScript/PHP as language but not Web in Platform
        web_language_entries = []
        ignored = ('0_ad.md', 'aussenposten.md', 'between.md', 'caesaria.md', 'cavepacker.md', 'citybound.md', 'gorillas.md', 'ika.md', 'inexor.md', 'maniadrive.md', 'oolite.md', 'freevikings.md', 'rolisteam.md', 'rpgboss.md', 'ruby-warrior.md', 'snelps.md', 'tenes_empanadas_graciela.md', 'thrive.md')
        for entry in self.entries:
            name = entry['File'].name
            if name in ignored:
                continue
            if any(language in entry['Code language'] for language in ('JavaScript', 'TypeScript', 'PHP', 'CoffeeScript')) and ('Platform' not in entry or 'Web' not in entry['Platform']):
                web_language_entries.append(entry['Title'])
        self._add_inconsistency_section(report_lines, 'Inconsistency: Java/Type/CoffeeScript/PHP as language but not Web in Platform', web_language_entries)

        # "Space" as part of the name but not "space" as keyword
        space_keyword_entries = []
        ignored = ('burgerspace.md', 'boardspacenet.md', 'crystal_space_3d_sdk.md', 'poland_can_into_space.md', 'our_personal_space.md', 'space_harrier_clone.md', 'spacecadetpinball.md')
        for entry in self.entries:
            name = entry['File'].name
            if name in ignored:
                continue
            title = entry['Title']
            if 'space' in title.lower() and 'space' not in entry['Keyword']:
                space_keyword_entries.append(entry['Title'])
        self._add_inconsistency_section(report_lines, 'Inconsistency: "Space" as part of the name but not "space" as keyword', space_keyword_entries)

        # Starts with j[A-Z] but not java as code language
        java_title_entries = []
        for entry in self.entries:
            title = entry['Title']
            if len(title) > 1 and title[0] == 'j' and title[1] == title[1].upper() and 'Java' not in entry['Code language']:
                java_title_entries.append(entry['Title'])
        self._add_inconsistency_section(report_lines, 'Inconsistency: Starts with j[A-Z] but not java as code language', java_title_entries)

        # Inconsistency: Duplicate keyword
        duplicate_keyword_entries = []
        for entry in self.entries:
            keywords = entry['Keyword']
            duplicates = [keyword for keyword in keywords if keywords.count(keyword) > 1]
            if duplicates:
                duplicate_keyword_entries.append(f'{entry["Title"]} ({", ".join(duplicates)})')
        self._add_inconsistency_section(report_lines, 'Inconsistency: Duplicate keyword', duplicate_keyword_entries)

        # entries without platform field
        missing_platform_entries = [entry['Title'] for entry in self.entries if 'Platform' not in entry]
        self._add_inconsistency_section(report_lines, 'Inconsistency: entries without platform field', missing_platform_entries)

        # entries without code repository
        missing_repo_entries = [entry['Title'] for entry in self.entries if 'Code repository' not in entry]
        self._add_inconsistency_section(report_lines, 'Inconsistency: entries without code repository', missing_repo_entries)

        # no popular first code repository service
        unpopular_repo_entries = []
        for entry in self.entries:
            repos = entry.get('Code repository', [])
            if repos and not self._is_popular_code_repository(str(repos[0])):
                unpopular_repo_entries.append(entry['Title'])
        self._add_inconsistency_section(report_lines, 'Inconsistency: no popular first code repository service', unpopular_repo_entries)

        # unknown code languages
        unknown_lang_entries = []
        for entry in self.entries:
            if 'Code language' in entry:
                for lang in entry['Code language']:
                    if lang not in c.known_languages:
                        unknown_lang_entries.append(f"{entry['Title']} ({lang})")
        self._add_inconsistency_section(report_lines, 'Inconsistency: unknown code languages', unknown_lang_entries)

        # unknown code licenses
        unknown_license_entries = []
        for entry in self.entries:
            if 'Code license' in entry:
                for lic in entry['Code license']:
                    if lic not in c.known_licenses:
                        unknown_license_entries.append(f"{entry['Title']} ({lic})")
        self._add_inconsistency_section(report_lines, 'Inconsistency: unknown code licenses', unknown_license_entries)

        # duplicate/unsorted developers
        developer_entries = []
        for entry in self.entries:
            if 'Developer' in entry:
                devs = entry['Developer']
                duplicates = [dev for dev in devs if devs.count(dev) > 1]
                sorted_devs = sorted(devs, key=str.casefold)
                if duplicates or devs != sorted_devs:
                    issues = []
                    if duplicates:
                        issues.append(f'duplicate developers: {set(duplicates)}')
                    if devs != sorted_devs:
                        issues.append('developers not sorted alphabetically')
                    developer_entries.append(f'{entry["Title"]} ({"; ".join(issues)})')
        self._add_inconsistency_section(report_lines, 'Inconsistency: duplicate/unsorted developers', developer_entries)

        # free assets license but not content open
        free_assets_no_content_open_entries = []
        for entry in self.entries:
            if self._has_open_assets_license(entry) and not self._has_content_open_keyword(entry):
                free_assets_no_content_open_entries.append(entry['Title'])
        self._add_inconsistency_section(report_lines, 'Inconsistency: free assets license but not content open', free_assets_no_content_open_entries)

        # content commercial keyword but not commercial assets license
        commercial_content_no_commercial_assets_entries = []
        for entry in self.entries:
            if self._has_commercial_content_keyword(entry) and not self._has_open_assets_license(entry):
                commercial_content_no_commercial_assets_entries.append(entry['Title'])
        self._add_inconsistency_section(report_lines, 'Inconsistency: content commercial keyword but not commercial assets license', commercial_content_no_commercial_assets_entries)

        # entry without screenshot
        screenshot_entries = []
        if c.screenshots_file.exists():
            screenshot_names = {line[2:].strip() for line in utils.read_text(c.screenshots_file).splitlines() if line.startswith('# ')}
            for entry in self.entries:
                file_name = entry['File'].name
                if file_name.endswith('.md'):
                    file_name = file_name[:-3]
                if file_name not in screenshot_names:
                    screenshot_entries.append(entry['Title'])
        self._add_inconsistency_section(report_lines, 'Inconsistency: entry without screenshot', screenshot_entries)

        report_text = '\n'.join(report_lines).rstrip() + '\n'
        utils.write_text(c.code_path / 'inconsistencies.txt', report_text)
        print(f'inconsistency report written to {c.code_path / "inconsistencies.txt"}')

    def clean_rejected(self):
        """
        Only sorts the rejected games list file removing duplicates.
        """
        # sort rejected games list file
        sort_text_file(c.root_path / 'code' / 'rejected.txt', 'rejected games list')

    def clean_backlog(self):
        """
        Goes through the backlog, removes if existing in an entry now, then sorts and removed duplicates.
        """
        if not self.entries:
            print('entries not yet loaded')
            return
        # get urls from entries
        included_urls = osg.all_urls(self.entries)
        included_urls = list(included_urls.keys())  # only need the URLs here

        # get urls from rejected file
        text = utils.read_text(c.rejected_file)
        regex = re.compile(r"\((http.*?)\)", re.MULTILINE)
        matches = regex.findall(text)
        rejected_urls = []
        for match in matches:
            urls = match.split(',')
            urls = [x.strip() for x in urls]
            rejected_urls.extend(urls)
        included_urls.extend(rejected_urls)

        # those that only have a web archive version, also get the original version
        more_urls = []
        for url in included_urls:
            if url.startswith('https://web.archive.org/web'):
                # print(url) # sometimes the http is missing in archive links (would need proper parsing)
                url = url[url.index('http', 5):]
                more_urls.append(url)
        included_urls.extend(more_urls)

        # now we strip the urls
        stripped_urls = [utils.strip_url(x) for x in included_urls]
        stripped_urls = set(stripped_urls)  # removes duplicates for performance

        # read backlog and get urls from there
        text = utils.read_text(c.backlog_file)
        text = text.split('\n')

        # remove those that are in stripped_game_urls
        text = [x for x in text if utils.strip_url(x) not in stripped_urls]

        # remove duplicates and sort
        text = sorted(list(set(text)), key=str.casefold)
        print(f'backlog contains {len(text)} items')

        # join and save again
        text = '\n'.join(text)
        utils.write_text(c.backlog_file, text)

        print('backlog cleaned')


    def check_external_links(self):
        """
        Checks all external links it can find for validity. Prints those with non OK HTTP responses. Does only need to be run
        from time to time.
        """

        # regex for finding urls (can be in <> or in ]() or after a whitespace
        # regex = re.compile(r"[\s]<(http.+?)>|\]\((http.+?)\)[^\)]|[\s](http.+?)[\s,]")
        regex = re.compile(r"\s<(http.+?)>|\]\((http\S+)\)|\s(http[^\(]+?)[\s,^\)]|\s(http\S+?\(\S+?\))[\s,]")

        # ignore the following patterns (they give false positives here)
        ignored_urls = (
        'https://git.tukaani.org/xz.git', 'https://git.code.sf.net/', 'http://hg.hedgewars.org/hedgewars/',
        'https://git.xiph.org/vorbis.git', 'http://svn.uktrainsim.com/svn/openrails', 'https://www.srb2.org/',
        'http://wiki.srb2.org/', 'https://web.archive.org/web/', 'https://www.comunidadargentum.com/',
        'http://www.argentumonline.com.ar/', 'https://www.atrinik.org/', 'https://mvnrepository.com/artifact/com.gitlab.bsarter.belote',
        'http://aegidian.org/bb/index.php', 'https://code.ur.gs/lupine/ordoor', 'https://git.tartarus.org/simon/puzzles')
        # especially the web archive links will be checked separately

        # some do redirect, but we nevertheless want the original URL in the database
        redirect_okay = ('https://octaforge.org/', 'https://svn.openttd.org/', 'https://godotengine.org/download', 'http://drive.google.com/uc?export=download&id=1chP3Yrey-jWJBz9bRllmsKBPVgxysCFQ', 'https://www.reddit.com/r/SuperTuxParty/')

        # extract all links from entries
        import urllib3
        urllib3.disable_warnings()  # otherwise we cannot verify those with SSL errors without getting warnings
        urls = {}
        for entry, _, content in osg.entry_iterator():
            # apply regex
            matches = regex.findall(content)
            # for each match
            for match in matches:
                for url in match:
                    if url and not any((url.startswith(x) for x in ignored_urls)):
                        # ignore bzr.sourceforge, no web address found
                        if 'bzr.sourceforge.net/bzrroot/' in url:
                            continue

                        # add "/" at the end
                        if any((url.startswith(x) for x in (
                        'https://anongit.freedesktop.org/git', 'https://git.savannah.gnu.org/git/',
                        'https://git.savannah.nongnu.org/git/', 'https://git.artsoft.org/'))):
                            url += '/'

                        if url.startswith('https://bitbucket.org/') and url.endswith('.git'):
                            url = url[:-4] + '/commits/'
                        if url.startswith('https://svn.code.sf.net/p/'):
                            url = 'http' + url[5:] + '/'
                        if url.startswith('http://cvs.savannah.nongnu.org:/sources/'):
                            url = 'http://cvs.savannah.nongnu.org/viewvc/' + url[40:] + '/'
                        if url.startswith('http://cvs.savannah.gnu.org:/sources/'):
                            url = 'http://cvs.savannah.gnu.org/viewvc/' + url[37:] + '/'

                        # generally ".git" at the end is not working well, except sometimes it actually does
                        if url.endswith('.git') and not any((url.startswith(x) for x in (
                        'https://repo.or.cz', 'https://git.tuxfamily.org'))):
                            url = url[:-4]

                        if url in urls:
                            urls[url].add(entry)
                        else:
                            urls[url] = {entry}
        print(f'found {len(urls)} unique links')
        print("start checking external links (can take a while)")

        # now iterate over all urls
        for url, names in urls.items():
            names = list(names)  # was a set
            if len(names) == 1:
                names = names[0]
            try:
                verify = True
                # some have an expired certificate but otherwise still work
                if any((url.startswith(x) for x in (
                'https://perso.b2b2c.ca/~sarrazip/dev/', 'https://dreerally.com/', 'https://henlin.net/',
                'https://www.megamek.org/', 'https://pixeldoctrine.com/', 'https://gitorious.org/',
                'https://www.opmon-game.ga/'))):
                    verify = False
                r = requests.head(url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64)'}, timeout=20,
                                  allow_redirects=True, verify=verify)
                if r.status_code in (403, 404, 405):  # head method not supported, try get (not only for 405, sometimes also works for 403, 404)
                    r = requests.get(url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64)'},
                                     timeout=20, allow_redirects=True, verify=verify)
                # check for bad status
                if r.status_code != requests.codes.ok:
                    print(f'{names}: {url} - {r.status_code}')
                # check for redirect
                if r.history and url not in redirect_okay:
                    # only / added or http->https sometimes
                    redirected_url = r.url
                    if redirected_url == url + '/':
                        output = '{}: {} -> {} - redirect "/" at end '
                    elif redirected_url == 'https' + url[4:]:
                        output = '{}: {} -> {} - redirect "https" at start'
                    else:
                        output = '{}: {} -> {} - redirect '
                    print(output.format(names, url, redirected_url))
            except Exception as e:
                error_name = type(e).__name__
                if error_name == 'SSLError' and any((url.startswith(x) for x in (
                'https://gitorious.org/', 'https://www.freedroid.org/download/'))):
                    continue  # even though verify is False, these errors still get through
                print(f'{names}: {url} - exception {error_name}')

        print('external links checked')

    def update_readme_tocs(self):
        """
        Recounts entries in sub categories and writes them to the readme.
        Also updates the _toc files in the categories directories.

        Note: The Readme must have a specific structure at the beginning, starting with "# Open Source Games" and ending
        on "A collection.."

        Needs to be performed regularly.
        """

        # completely delete content of toc path
        for file in c.tocs_path.iterdir():
            file.unlink()

        # read readme
        readme_file = c.root_path / 'README.md'
        readme_text = utils.read_text(readme_file)

        # compile regex for identifying the building blocks in the readme
        regex = re.compile(r"(.*?)(\[comment\]: # \(start.*?end of autogenerated content\))(.*)", re.DOTALL)

        # apply regex
        matches = regex.findall(readme_text)
        if len(matches) != 1:
            raise RuntimeError('readme file has invalid structure')
        matches = matches[0]
        start = matches[0]
        end = matches[2]

        tocs_text = ''

        # split into games, tools, frameworks, libraries
        games = [x for x in self.entries if not any([y in x['Keyword'] for y in ('tool', 'framework', 'library')])]
        tools = [x for x in self.entries if 'tool' in x['Keyword']]
        frameworks = [x for x in self.entries if 'framework' in x['Keyword']]
        libraries = [x for x in self.entries if 'library' in x['Keyword']]
        
        # create games, tools, frameworks, libraries tocs
        title = 'Games'
        file = '_games.md'
        tocs_text += f'**[{title}](entries/tocs/{file}#{title})** ({len(games)}) - '
        create_toc(title, file, games)

        title = 'Tools'
        file = '_tools.md'
        tocs_text += f'**[{title}](entries/tocs/{file}#{title})** ({len(tools)}) - '
        create_toc(title, file, tools)

        title = 'Frameworks'
        file = '_frameworks.md'
        tocs_text += f'**[{title}](entries/tocs/{file}#{title})** ({len(frameworks)}) - '
        create_toc(title, file, frameworks)

        title = 'Libraries'
        file = '_libraries.md'
        tocs_text += f'**[{title}](entries/tocs/{file}#{title})** ({len(libraries)})\n'
        create_toc(title, file, libraries)

        # create by category
        categories_text = []
        for keyword in c.recommended_keywords:
            filtered = [x for x in self.entries if keyword in x['Keyword']]
            title = keyword.capitalize()
            name = keyword.replace(' ', '-')
            file = f'_{name}.md'
            categories_text.append(f'**[{title}](entries/tocs/{file}#{name})** ({len(filtered)})')
            create_toc(title, file, filtered)
        categories_text.sort()
        tocs_text += f"\nBy category: {', '.join(categories_text)}\n"

        # create by platform
        platforms_text = []
        for platform in c.valid_platforms:
            filtered = [x for x in self.entries if platform in x.get('Platform', [])]
            title = platform
            name = platform.lower()
            file = f'_{name}.md'
            platforms_text.append(f'**[{title}](entries/tocs/{file}#{name})** ({len(filtered)})')
            create_toc(title, file, filtered)
        tocs_text += f"\nBy platform: {', '.join(platforms_text)}\n"

        # insert new text in the middle (the \n before the second comment is necessary, otherwise Markdown displays it as part of the bullet list)
        text = start + "[comment]: # (start of autogenerated content, do not edit)\n" + tocs_text + "\n[comment]: # (end of autogenerated content)" + end

        # write to readme
        utils.write_text(readme_file, text)

        print('Readme and TOCs updated')

    def update_statistics(self):
        """
        Generates the statistics page.

        Should be done every time the entries change.
        """
        if not self.entries:
            print('entries not yet loaded')
            return

        # start the page
        statistics = '[comment]: # (autogenerated content, do not edit)\n# Statistics\n\n'

        # total number
        number_entries = len(self.entries)
        fraction = lambda x: x / number_entries * 100  # conversion to percent

        statistics += 'analyzed {} entries on {}\n\n'.format(number_entries,
                                                             datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'))

        # State (beta, mature, inactive)
        statistics += '## State\n\n'

        number_state_beta = sum(1 for x in self.entries if 'beta' in x['State'])
        number_state_mature = sum(1 for x in self.entries if 'mature' in x['State'])
        number_inactive = sum(1 for x in self.entries if osg.is_inactive(x))
        statistics += '- mature: {} ({:.1f}%)\n- beta: {} ({:.1f}%)\n- inactive: {} ({:.1f}%)\n\n'.format(
            number_state_mature, fraction(number_state_mature), number_state_beta, fraction(number_state_beta), number_inactive,
            fraction(number_inactive))

        if number_inactive > 0:
            entries_inactive = [(x['Title'], osg.extract_inactive_year(x)) for x in self.entries if osg.is_inactive(x)]
            entries_inactive.sort(key=lambda x: str.casefold(x[0]))  # first sort by name
            entries_inactive.sort(key=lambda x: x[1], reverse=True)  # then sort by inactive year (more recently first)
            entries_inactive = ['{} ({})'.format(*x) for x in entries_inactive]
            statistics += '##### Inactive State\n\n' + ', '.join(entries_inactive) + '\n\n'

        # Language
        statistics += '## Code Languages\n\n'
        field = 'Code language'

        # get all languages together
        languages = []
        for entry in self.entries:
            languages.extend(entry[field])

        unique_languages = set(languages)
        unique_languages = [(l, languages.count(l) / len(languages)) for l in unique_languages]
        unique_languages.sort(key=lambda x: str.casefold(x[0]))  # first sort by name

        # print languages to console
        print('\nLanguages\n')
        print('\n'.join(f'{x[0]} ({x[1] * 100:.1f}%)' for x in unique_languages))

        unique_languages.sort(key=lambda x: x[1], reverse=True)  # then sort by occurrence (highest occurrence first)
        unique_languages = [f'- {x[0]} ({x[1] * 100:.1f}%)\n' for x in unique_languages]
        statistics += '##### Language frequency\n\n' + ''.join(unique_languages) + '\n'

        # Licenses
        statistics += '## Code licenses\n\n'
        field = 'Code license'

        # get all licenses together
        licenses = []
        for entry in self.entries:
            licenses.extend(entry[field])

        unique_licenses = set(licenses)
        unique_licenses = [(l, licenses.count(l) / len(licenses)) for l in unique_licenses]
        unique_licenses.sort(key=lambda x: str.casefold(x[0]))  # first sort by name

        # print licenses to console
        print('\nLicenses\n')
        print('\n'.join(f'{x[0]} ({x[1] * 100:.1f}%)' for x in unique_licenses))

        unique_licenses.sort(key=lambda x: -x[1])  # then sort by occurrence (highest occurrence first)
        unique_licenses = [f'- {x[0]} ({x[1] * 100:.1f}%)\n' for x in unique_licenses]
        statistics += '##### Licenses frequency\n\n' + ''.join(unique_licenses) + '\n'

        # Keywords
        statistics += '## Keywords\n\n'
        field = 'Keyword'

        # get all keywords together
        keywords = []
        for entry in self.entries:
            keywords.extend(entry[field])

        # reduce those starting with "multiplayer"
        keywords = [x if not x.startswith('multiplayer') else 'multiplayer' for x in keywords]

        # for content keyword filter out everything in parentheses
        keywords = [x if not any(x.startswith(y) for y in ('content', 'original required')) else re.sub(r'\(.*?\)\s*', '', x) for x in keywords]

        unique_keywords = set(keywords)
        unique_keywords = [(l, keywords.count(l) / len(keywords)) for l in unique_keywords]
        unique_keywords.sort(key=lambda x: str.casefold(x[0]))  # first sort by name

        # print keywords to console
        print('\nKeywords\n')
        print('\n'.join(f'{x[0]} ({x[1] * 100:.1f}%)' for x in unique_keywords))

        unique_keywords.sort(key=lambda x: -x[1])  # then sort by occurrence (highest occurrence first)
        unique_keywords = [f'- {x[0]} ({x[1] * 100:.1f}%)' for x in unique_keywords]
        statistics += '##### Keywords frequency\n\n' + '\n'.join(unique_keywords) + '\n\n'

        # no download or play field
        statistics += '## Entries without download or play fields\n\n'

        entries = []
        for entry in self.entries:
            if 'Download' not in entry and 'Play' not in entry:
                entries.append(entry['Title'])
        entries.sort(key=str.casefold)
        statistics += f'{len(entries)}: ' + ', '.join(entries) + '\n\n'

        # code hosted not on github, gitlab, bitbucket, launchpad, sourceforge
        popular_code_repositories = ('github.com', 'gitlab.com', 'codeberg.org', 'code.sf.net')
        statistics += '## Entries with a code repository not on a popular site\n\n'

        entries = []
        field = 'Code repository'
        for entry in self.entries:
            popular = False
            for repo in entry.get(field, []):
                for popular_repo in popular_code_repositories:
                    if popular_repo in repo:
                        popular = True
                        break
            # if there were repositories, but none popular, add them to the list
            if not popular:
                entries.append(entry['Title'])
                # print(info[field])
        entries.sort(key=str.casefold)
        statistics += f'{len(entries)}: ' + ', '.join(entries) + '\n\n'

        # Code dependencies
        statistics += '## Code dependencies\n\n'
        field = 'Code dependency'

        # get all code dependencies together
        code_dependencies = []
        entries_with_code_dependency = 0
        for entry in self.entries:
            if field in entry:
                code_dependencies.extend(entry[field])
                entries_with_code_dependency += 1
        statistics += 'With code dependency field {} ({:.1f}%)\n\n'.format(entries_with_code_dependency,
                                                                           fraction(entries_with_code_dependency))

        unique_code_dependencies = set(code_dependencies)
        unique_code_dependencies = [(l, code_dependencies.count(l) / len(code_dependencies)) for l in
                                    unique_code_dependencies]
        unique_code_dependencies.sort(key=lambda x: str.casefold(x[0]))  # first sort by name

        # print code dependencies to console
        print('\nCode dependencies\n')
        print('\n'.join(f'{x[0]} ({x[1] * 100:.1f}%)' for x in unique_code_dependencies))

        unique_code_dependencies.sort(key=lambda x: -x[1])  # then sort by occurrence (highest occurrence first)
        unique_code_dependencies = [f'- {x[0]} ({x[1] * 100:.1f}%)' for x in unique_code_dependencies]
        statistics += '##### Code dependencies frequency\n\n' + '\n'.join(unique_code_dependencies) + '\n\n'

        # Build systems:
        statistics += '## Build systems\n\n'
        field = 'Build system'

        # get all build systems together
        build_systems = []
        for entry in self.entries:
            if field in entry['Building']:
                build_systems.extend(entry['Building'][field])

        statistics += 'Build systems information available for {:.1f}% of all projects.\n\n'.format(
            fraction(len(build_systems)))

        unique_build_systems = set(build_systems)
        unique_build_systems = [(l, build_systems.count(l) / len(build_systems)) for l in unique_build_systems]
        unique_build_systems.sort(key=lambda x: str.casefold(x[0]))  # first sort by name

        # print build systems to console
        print('\nBuild systems\n')
        print('\n'.join(f'{x[0]} ({x[1] * 100:.1f}%)' for x in unique_build_systems))

        unique_build_systems.sort(key=lambda x: -x[1])  # then sort by occurrence (highest occurrence first)
        unique_build_systems = [f'- {x[0]} ({x[1] * 100:.1f}%)' for x in unique_build_systems]
        statistics += f'##### Build systems frequency ({len(build_systems)})\n\n' + '\n'.join(
            unique_build_systems) + '\n\n'

        # C, C++ projects without build system information
        c_cpp_project_without_build_system = []
        for entry in self.entries:
            if field not in entry['Building'] and ('C' in entry['Code language'] or 'C++' in entry['Code language']):
                c_cpp_project_without_build_system.append(entry['Title'])
        c_cpp_project_without_build_system.sort(key=str.casefold)
        statistics += f'##### C and C++ projects without build system information ({len(c_cpp_project_without_build_system)})\n\n' + ', '.join(c_cpp_project_without_build_system) + '\n\n'

        # C, C++ projects with build system information but without CMake as build system
        c_cpp_project_not_cmake = []
        for entry in self.entries:
            # if (field in entry) and (not 'CMake' in entry[field] and ('C' in entry['Code language'] or 'C++' in entry['Code language']):
            if (field in entry['Building']) and (not 'CMake' in entry['Building'][field]) and ('C' in entry['Code language'] or 'C++' in entry['Code language']):
                c_cpp_project_not_cmake.append(entry['Title'])
        c_cpp_project_not_cmake.sort(key=str.casefold)
        statistics += f'##### C and C++ projects with a build system different from CMake ({len(c_cpp_project_not_cmake)})\n\n' + ', '.join(c_cpp_project_not_cmake) + '\n\n'

        # Platform
        statistics += '## Platform\n\n'
        field = 'Platform'

        # get all platforms together
        platforms = []
        number_entries_with_platform = 0
        for entry in self.entries:
            if field in entry:
                number_entries_with_platform += 1
                platforms.extend(entry[field])

        statistics += f'Platform information available for {fraction(number_entries_with_platform):.1f}% of all projects.\n\n'

        unique_platforms = set(platforms)
        unique_platforms = [(l, fraction(platforms.count(l))) for l in unique_platforms]
        unique_platforms.sort(key=lambda x: str.casefold(x[0]))  # first sort by name
        unique_platforms.sort(key=lambda x: -x[1])  # then sort by occurrence (highest occurrence first)
        unique_platforms = [f'- {x[0]} ({x[1]:.1f}%)' for x in unique_platforms]
        statistics += '##### Platforms frequency\n\n' + '\n'.join(unique_platforms) + '\n\n'

        # write to statistics file
        utils.write_text(c.statistics_file, statistics)

        print('statistics updated')

    def update_repos(self):
        """
        Export to json for local repository update of primary repos
        """
        if not self.entries:
            print('entries not yet loaded')
            return

        primary_repos = {'git': [], 'svn': [], 'hg': []}
        unconsumed_entries = []

        # for every entry filter those that are known git repositories (add additional repositories)
        for entry in self.entries:
            repos = entry.get('Code repository', [])
            # keep the first and all others containing @add in comment
            if not repos:
                continue
            repos = [repos[0]] + [x for x in repos[1:] if isinstance(x, osg_parse.Value) and "@add" in x.comment]
            for repo in repos:
                consumed = False
                repo = repo.split(' ')[0].strip()
                url = osg.get_git_repo(repo)
                if url:
                    primary_repos['git'].append(url)
                    consumed = True
                    continue
                url = osg.get_svn_repo(repo)
                if url:
                    primary_repos['svn'].append(url)
                    consumed = True
                    continue
                url = osg.get_hg_repo(repo)
                if url:
                    primary_repos['hg'].append(url)
                    consumed = True
                    continue

                if not consumed:
                    unconsumed_entries.append([entry['Title'], repo])
                    print(f"Entry \"{entry['File']}\" unconsumed repo: {repo}")

        # sort them alphabetically (and remove duplicates)
        for k, v in primary_repos.items():
            primary_repos[k] = sorted(set(v))

        # statistics of gits
        git_repos = primary_repos['git']
        print(f'{len(git_repos)} Git repositories')
        for domain in (
                'repo.or.cz', 'anongit.kde.org', 'bitbucket.org', 'git.code.sf.net', 'git.savannah', 'git.tuxfamily',
                'github.com',
                'gitlab.com', 'gitlab.com/osgames', 'gitlab.gnome.org'):
            print(f'{sum(1 if domain in x else 0 for x in git_repos)} on {domain}')

        # write them to code/git
        json_path = c.root_path / 'code' / 'archives.json'
        text = json.dumps(primary_repos, indent=1)
        utils.write_text(json_path, text)

        print('Repositories updated')

    def collect_git_repos(self):
        """
        For every entry, get all git references.
        """
        if not self.entries:
            print('entries not yet loaded')
            return
        
        git_repos = []
        for entry in self.entries:
            repos = entry['Code repository']
            for repo in repos:
                repo = repo.split(' ')[0].strip()
                url = osg.get_git_repo(repo)
                if url:
                    git_repos.append(repo)

        # sort them alphabetically (and remove duplicates)
        git_repos = sorted(list(set(git_repos)), key=str.casefold)

        # write them to code/git
        json_path = c.root_path / 'code' / 'git_repositories.json'
        text = json.dumps(git_repos, indent=1)
        utils.write_text(json_path, text)

    def custom_action(self):
        """
        For special operations that are one-time and may change.
        :return:
        """
        if not self.entries:
            print('entries not yet loaded')
            return

        # # which fields have lots of comments
        # for field in c.valid_fields:
        #     values = [value for entry in self.entries for value in entry.get(field, [])]
        #     if isinstance(values[0], osg_parse.ValueWithComment):
        #         comments = [value.comment for value in values if value.comment]
        #         # split by comma
        #         comments = [c.strip() for comment in comments for c in comment.split(',')]
        #         print('field {} has {} comments'.format(field, len(comments)))
        #         for comment in set(comments):
        #             print('  {} - {}'.format(comment, comments.count(comment)))

        # # remove download urls that are also in home
        # for entry in self.entries:
        #     homes = entry['Home']
        #     downloads = entry.get('Download', [])
        #     downloads = [download for download in downloads if download not in homes]
        #     if downloads:
        #         entry['Download'] = downloads
        #     if not downloads and 'Download' in entry:
        #         del entry['Download']

        # remove developers from all that have library as keyword
        for entry in self.entries:
            if 'library' in entry['Keyword']:
                devs = entry.get('Developer', [])
                if devs:
                    print(f"entry {entry['File']} is library and has {len(devs)} developer")
                    del entry['Developer']

        # # collect statistics on git repositories
        # stats = {}
        # for entry in self.entries:
        #     repos = entry.get('Code repository', [])
        #     comments = [x.comment for x in repos if x.startswith('https://github.com/') and x.comment]
        #     for comment in comments:
        #         for part in comment.split(','):
        #             part = part.strip()
        #             if not part.startswith('@'):
        #                 continue
        #             part = part.split(' ')
        #             key = part[0][1:]  # without the @
        #             value = part[1] if len(part) > 1 else None
        #             stats[key] = stats.get(key, []) + [value]
        # # process statistics
        # stats['archived'] = len(stats['archived'])
        # created = stats['created']
        # stats['created'] = {}
        # for year in created:
        #     stats['created'][year] = stats['created'].get(year, 0) + 1
        #
        # for key, value in sorted(stats['created'].items(), key=lambda x: x[0]):
        #     print("{} : {}".format(key, value))
        #
        # import numpy as np
        # np.set_printoptions(suppress=True)
        # stars = np.array(stats['stars'], dtype=np.float)
        # forks = np.array(stats['forks'], dtype=np.float)
        # q = np.arange(0, 1, 0.333)
        # print(q)
        # print(np.quantile(stars, q))
        # print(np.quantile(forks, q))

        # # cvs without any git
        # for entry in self.entries:
        #     repos = entry['Code repository']
        #     cvs = [repo for repo in repos if 'cvs' in repo]
        #     git = [repo for repo in repos if 'git' in repo]
        #     if len(cvs) > 0 and len(git) == 0:
        #         print('Entry "{}" with repos: {}'.format(entry['File'], repos))

        # # combine content keywords
        # n = len('content ')
        # for entry in self.entries:
        #     keywords = entry['Keyword']
        #     content = [keyword for keyword in keywords if keyword.startswith('content')]
        #     if len(content) > 1:
        #         # remove from keywords
        #         keywords = [keyword for keyword in keywords if keyword not in content]
        #         # remove prefix
        #         content = [str(keyword)[n:].strip() for keyword in content]
        #         # join with +
        #         content = 'content {}'.format(' + '.join(content))
        #         keywords.append(osg_parse.ValueWithComment(content))
        #         entry['Keyword'] = keywords
        #         print('fixed "{}"'.format(entry['File']))

        print('special ops finished')

if __name__ == "__main__":

    m = EntriesMaintainer()

    actions = {
        'Read entries': m.read_entries,
        'Write entries': m.write_entries,
        'Check template leftovers': m.check_template_leftovers,
        'Check inconsistencies': m.check_inconsistencies,
        'Check rejected entries': m.clean_rejected,
        'Check external links (takes quite long)': m.check_external_links,
        'Clean backlog': m.clean_backlog,
        'Update Readme and TOCs': m.update_readme_tocs,
        'Update statistics': m.update_statistics,
        'Update repository list': m.update_repos,
        'Custom': m.custom_action,
    }

    osg_ui.run_simple_button_app('Entries developer', actions)


