name: Parse metadata

on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  parse-metadata:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Pip install
        run: |
          cd code
          pip install -r requirements.txt

      - name: Parse entries
        run: |
          cd code
          python3 -c "from utils.osg import read_entries; read_entries()"

      - name: Parse inspirations
        run: |
          cd code
          python3 -c "from utils.osg import read_inspirations; read_inspirations()"
          
      - name: Parse developers
        run: |
          cd code
          python3 -c "from utils.osg import read_developers; read_developers()"
